---
theme: jekyll-theme-minimal
title: VDOT Habitat Technical Working Group
description: A repository for documents and data shared between CCRM and VDOT staff in the Habitat Technical Working Group
logo: VDOTHabitatTechnical/Figures/ccrm.jpg
---

# VDOTHabitatTechnical
Data and documentation shared among the VDOT Habitat Technical Advisory Group.


## Project contacts:
### CCRM Habitat co-leads:
> Donna Bilkovic - [donnab@vims.edu](mailto:donnab@vims.edu) 

> Kory Angstadt - kory@vims.edu 

### CCRM Support staff: 
> Robert Isdell - risdell@vims.edu

> Christine Tombleson - christine@vims.edu

> Julie Herman - herman@vims.edu

### VDOT Advisory members: 
> Amy O'Leary - Amy.Oleary@vdot.virginia.gov 

> Dan Redgate - daniel.redgate@vdot.virginia.gov 
